# Generated by Django 4.0.5 on 2024-01-25 00:42

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_blogindexpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='body',
            new_name='approach',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='challen',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='results',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
