# Generated by Django 4.0.5 on 2024-01-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_body_blogpage_approach_blogpage_challen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(max_length=450),
        ),
    ]
