services:
- type: web
  name: portfolio
  env: python
  plan: starter
  buildCommand: ./build.sh
  startCommand: gunicorn portfolio.wsgi:application
  envVars:
    - key: WEB_CONCURRENCY
      value: 4
    - key: DATABASE_URL
      value: "postgres://ldiqtjul:WQP8bzA_-4Nhww65rpXumlwfhsPhU7d1@hattie.db.elephantsql.com/ldiqtjul"
    # - key: DJANGO_SECRET_KEY
    - key: SECRET_KEY
      generateValue: true
    - key: DJANGO_ADMIN_URL
      generateValue: true
    - key: DJANGO_SETTINGS_MODULE
      value: portfolio.settings.prod

databases:
- name: portfolio
  databaseName: django
  user: django
