# Generated by Django 4.0.5 on 2024-01-12 19:14

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_options_homepage_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about2',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
