# Generated by Django 4.0.5 on 2024-01-17 22:24

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_about2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='about2',
            new_name='education',
        ),
        migrations.AddField(
            model_name='homepage',
            name='experience',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
